apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: ALLOW_EMPTY_PASSWORD
        {{- if .Values.allowEmptyPassword }}
          value: "yes"
        {{- else }}
          value: "no"
        {{- end }}
        - name: MYSQL_WP_HOST
        {{- if .Values.mariadb.enabled }}
          value: {{ template "mariadb.fullname" . }}
        {{- else }}
          value: {{ .Values.externalDatabase.host | quote }}
        {{- end }}
        - name: MYSQL_WP_DBNAME
        {{- if .Values.mariadb.enabled }}
          value: {{ .Values.mariadb.db.name | quote }}
        {{- else }}
          value: {{ .Values.externalDatabase.database | quote }}
        {{- end }}
        - name: MYSQL_WP_USER
        {{- if .Values.mariadb.enabled }}
          value: {{ .Values.mariadb.db.user | quote }}
        {{- else }}
          value: {{ .Values.externalDatabase.user | quote }}
        {{- end }}
        - name: MYSQL_WP_PASSWORD
          valueFrom:
            secretKeyRef:
            {{- if .Values.mariadb.enabled }}
              name: {{ template "mariadb.fullname" . }}
              key: mariadb-password
            {{- else }}
              name: {{ printf "%s-%s" .Release.Name "externaldb" }}
              key: db-password
            {{- end }}
        
        - name: WP_TITLE
          value: {{ .Values.applicationTitle | quote }}
        - name: WP_ADMIN_USER
          value: {{ .Values.applicationAdminUsername | quote }}
        - name: WP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: application-admin-password
        - name: WP_ADMIN_EMAIL
          value: {{ .Values.applicationAdminEmail | quote }}
        - name: WP_HTTPS
          value: {{ .Values.applicationHTTPS | quote }}
        - name: WP_URL
          value: {{ .Values.applicationStagingURL | quote }}
        - name: WP_ALIAS
          value: {{ .Values.applicationAlias | quote }}
        - name: WP_LIVE
          value: {{ .Values.applicationLive | quote }}
        - name: WP_CDN
          value: {{ .Values.applicationCDN | quote }}
        - name: S3WAAS_APP_TAG
          value: {{ .Values.applicationTag | quote }}

        - name: WP_FIND_URL
          value: {{ .Values.applicationMasterURL | quote }}
        - name: WP_LANG_NAME
          value: {{ .Values.applicationLanguageName | quote }}
        - name: WP_LANG_CODE
          value: {{ .Values.applicationLanguageCode | quote }}
        - name: WP_LANG_LOCALE
          value: {{ .Values.applicationLanguageLocale | quote }}
        - name: WP_THEME_NAME
          value: {{ .Values.applicationThemeName | quote }}

        - name: S3_UPLOADS_BUCKET
          value: {{ .Values.applicationS3UploadsBucket | quote }}
        - name: S3_UPLOADS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: object-storage-key
        - name: S3_UPLOADS_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: object-storage-secret
        - name: S3_UPLOADS_REGION
          value: {{ .Values.applicationS3UploadsRegion | quote }}
        - name: S3_UPLOADS_ENDPOINT
          value: {{ .Values.applicationS3UploadsEndpoint | quote }}
        - name: S3_UPLOADS_BUCKET_URL
          value: {{ .Values.applicationS3UploadsBucketURL | quote }}
        - name: S3_UPLOADS_CDN_URL
          value: {{ .Values.applicationS3UploadsCDNURL | quote }}

        # - name: SMTP_HOST
        #   value: {{ .Values.smtpHost | quote }}
        # - name: SMTP_PORT
        #   value: {{ .Values.smtpPort | quote }}
        # - name: SMTP_USER
        #   value: {{ .Values.smtpUser | quote }}
        # - name: SMTP_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: {{ template "fullname" . }}
        #       key: smtp-password
        # - name: SMTP_USERNAME
        #   value: {{ .Values.smtpUsername | quote }}
        # - name: SMTP_PROTOCOL
        #   value: {{ .Values.smtpProtocol | quote }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /version.php
          {{- if not .Values.healthcheckHttps }}
            port: http
          {{- else }}
            port: https
            scheme: HTTPS
          {{- end }}
{{ toYaml .Values.livenessProbe | indent 10 }}
        readinessProbe:
          httpGet:
            path: /version.php
          {{- if not .Values.healthcheckHttps }}
            port: http
          {{- else }}
            port: https
            scheme: HTTPS
          {{- end }}
{{ toYaml .Values.readinessProbe | indent 10 }}
        volumeMounts:
        - mountPath: {{ .Values.applicationMountPath }}
          name: s3waas-state-app-code
          readOnly: true
        #   subPath: apache
        # - mountPath: /bitnami/wordpress
        #   name: wordpress-data
        #   subPath: wordpress
        # - mountPath: /bitnami/php
        #   name: wordpress-data
        #   subPath: php
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: s3waas-state-app-code
        hostPath: 
          path: {{ .Values.applicationMountPath }}
          type: ""
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{ end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end -}}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

